dist: trusty 
language: java
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/.gradle
install: true

before_install:
  - wget -q -O - https://download.bell-sw.com/pki/GPG-KEY-bellsoft | sudo apt-key add -
  - echo "deb [arch=amd64] https://apt.bell-sw.com/ stable main" | sudo tee /etc/apt/sources.list.d/bellsoft.list
  - sudo apt-get -qq update
  - sudo apt-get -y install bellsoft-java11

script:
  - ./gradlew clean test
