package org.laeq.model.statistic;

import javafx.util.Duration;
import org.laeq.model.Point;

import javax.annotation.Nullable;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Matching point generated by Tarjan algorithm.
 *
 * If one point is @Null
 *
 */
public class MatchedPoint {
    public Point pt1;
    public Point pt2;

    public MatchedPoint(){

    }

    /**
     * Get 2 matching points
     *
     * @return Boolean
     */
    public Boolean matched(){
        if(this.pt1 != null && this.pt2 != null){
            return Boolean.TRUE;
        }

        return Boolean.FALSE;
    }

    public List<Duration> getStarts(){
        List<Duration> result = new ArrayList<>();
        if(matched()){
            result.add(pt1.getStart());
            result.add(pt2.getStart());
        } else {
            result.add(getPoint().getStart());
        }

        return result.stream().sorted().collect(Collectors.toList());
    }

    /**
     * Get unmatched point
     * @return
     */
    public Boolean unmatchedVideo1(){
        return ! matched() && pt1 != null;
    }

    /**
     * Get unmatched point
     * @return
     */
    public Boolean unmatchedVideo2(){
        return ! matched() && pt2 != null;
    }

    public String getPt1Formatted(){
        return pt1 != null ? pt1.getStartFormatted() : "";
    }

    public String getPt2Formatted(){
        return pt2 != null ? pt2.getStartFormatted() : "";
    }

    /**
     * Get non null point
     * @return Point
     */
    public Point getPoint() {
        return pt1 != null ? pt1 : pt2;
    }
}
