package org.laeq.model.statistic;

import org.laeq.model.Point;

import javax.annotation.Nullable;

/**
 * Matching point generated by Tarjan algorithm.
 *
 * If one point is @Null
 *
 */
public class MatchedPoint {
    public Point pt1;
    public Point pt2;

    public MatchedPoint(){

    }

    /**
     * Get 2 matching points
     *
     * @return Boolean
     */
    public Boolean matched(){
        if(this.pt1 != null && this.pt2 != null){
            return Boolean.TRUE;
        }

        return Boolean.FALSE;
    }

    /**
     * Get unmatched point
     * @return
     */
    public Boolean unmatchedVideo1(){
        return ! matched() && pt1 != null;
    }

    /**
     * Get unmatched point
     * @return
     */
    public Boolean unmatchedVideo2(){
        return ! matched() && pt2 != null;
    }

    public String getPt1Formatted(){
        return pt1 != null ? pt1.getStartFormatted() : "";
    }

    public String getPt2Formatted(){
        return pt2 != null ? pt2.getStartFormatted() : "";
    }

    /**
     * Get non null point
     * @return Point
     */
    public Point getPoint() {
        return pt1 != null ? pt1 : pt2;
    }
}
