CREATE SEQUENCE IF NOT EXISTS  category_id  AS INTEGER START WITH 1 INCREMENT BY 1 NO CYCLE MINVALUE 1;
CREATE SEQUENCE IF NOT EXISTS  user_id  AS INTEGER START WITH 1 INCREMENT BY 1 NO CYCLE MINVALUE 1;
CREATE SEQUENCE IF NOT EXISTS  point_id  AS INTEGER START WITH 1 INCREMENT BY 1 NO CYCLE MINVALUE 1;
CREATE SEQUENCE IF NOT EXISTS  video_id  AS INTEGER START WITH 1 INCREMENT BY 1 NO CYCLE MINVALUE 1;
CREATE SEQUENCE IF NOT EXISTS  category_collection_id AS INTEGER START WITH 1 INCREMENT BY 1 NO CYCLE MINVALUE 1;
CREATE SEQUENCE IF NOT EXISTS  icon_id AS INTEGER START WITH 1 INCREMENT BY 1 NO CYCLE MINVALUE 1;