DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS VIDEO;
DROP TABLE IF EXISTS POINT;
DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
   ID int NOT NULL PRIMARY KEY,
   NAME varchar(30) NOT NULL
);

CREATE TABLE CATEGORY (
   ID int NOT NULL PRIMARY KEY,
   NAME varchar(30) NOT NULL,
   ICON varchar(255) NOT NULL,
   SHORTCUT varchar(1) NOT NULL
);

CREATE TABLE VIDEO (
   ID int NOT NULL PRIMARY KEY,
   NAME varchar(30) NOT NULL,
);

CREATE TABLE POINT (
 ID int NOT NULL PRIMARY KEY,
 X double NOT NULL,
 Y double NOT NULL,
 VIDEO_ID int NOT NULL,
 USER_ID int NOT NULL,
 CATEGORY_ID int NOT NULL,
 millis double NOT NULL
);