CREATE TABLE IF NOT EXISTS USER (
       ID int NOT NULL PRIMARY KEY,
       FIRST_NAME varchar(30) NOT NULL,
       LAST_NAME varchar(30) NOT NULL,
       EMAIL varchar(100) NOT NULL,
       CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
       UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
       UNIQUE(FIRST_NAME, LAST_NAME, EMAIL)
);

CREATE TABLE IF NOT EXISTS CATEGORY (
       ID int NOT NULL PRIMARY KEY,
       NAME varchar(30) NOT NULL,
       ICON varchar(3000) NOT NULL,
       SHORTCUT varchar(1) NOT NULL,
       CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
       UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
       CONSTRAINT category_shortcut_uniq UNIQUE (SHORTCUT),
       UNIQUE (NAME, ICON)
);

CREATE TABLE IF NOT EXISTS VIDEO (
       ID int NOT NULL PRIMARY KEY,
       PATH varchar(3000) NOT NULL,
       DURATION DOUBLE NOT NULL,
       CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
       UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS POINT (
     ID int NOT NULL PRIMARY KEY,
     X double NOT NULL,
     Y double NOT NULL,
     VIDEO_ID int NOT NULL,
     USER_ID int NOT NULL,
     CATEGORY_ID int NOT NULL,
     START double NOT NULL,
     CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
     CONSTRAINT point_video FOREIGN KEY (VIDEO_ID) REFERENCES VIDEO (ID) ON DELETE CASCADE,
     CONSTRAINT point_user FOREIGN KEY (USER_ID) REFERENCES USER (ID) ON DELETE CASCADE,
     CONSTRAINT point_category FOREIGN KEY (CATEGORY_ID) REFERENCES USER (ID) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS CATEGORY_COLLECTION(
    ID int NOT NULL PRIMARY KEY,
    NAME varchar(30) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE (NAME)
);

CREATE TABLE IF NOT EXISTS CATEGORY_COLLECTION_CATEGORY(
    CATEGORY_COLLECTION_ID int NOT NULL,
    CATEGORY_ID int NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT cat_col_key_1 FOREIGN KEY (CATEGORY_COLLECTION_ID) REFERENCES CATEGORY_COLLECTION (ID) ON DELETE CASCADE,
    CONSTRAINT cat_col_key_2 FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID) ON DELETE CASCADE,
    UNIQUE (CATEGORY_COLLECTION_ID, CATEGORY_ID)
);
