DROP TABLE IF EXISTS POINT;
DROP TABLE IF EXISTS VIDEO;
DROP TABLE IF EXISTS CATEGORY_COLLECTION_CATEGORY;
DROP TABLE IF EXISTS CATEGORY_COLLECTION;
DROP TABLE IF EXISTS VIDEO_USER;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS USER;

DROP SEQUENCE IF EXISTS user_id;
DROP SEQUENCE IF EXISTS point_id;
DROP SEQUENCE IF EXISTS video_id;
DROP SEQUENCE IF EXISTS category_id;
DROP SEQUENCE IF EXISTS video_user_id;
DROP SEQUENCE IF EXISTS category_collection_id;

