DROP TABLE IF EXISTS POINT;
DROP TABLE IF EXISTS VIDEO;
DROP TABLE IF EXISTS CATEGORY_COLLECTION;
DROP TABLE IF EXISTS COLLECTION;
DROP TABLE IF EXISTS VIDEO_USER;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS USER;


