import griffon.util.AbstractMapResourceBundle;

import javax.annotation.Nonnull;
import java.util.Map;

import static griffon.util.CollectionUtils.map;
import static java.util.Arrays.asList;

public class Config extends AbstractMapResourceBundle {
    @Override
    protected void initialize(@Nonnull Map<String, Object> entries) {
        map(entries)
            .e("application", map()
                .e("title", "vifeco")
                .e("startupGroups", asList("vifeco"))
                .e("autoShutdown", true)
            )
            .e("mvcGroups", map()
                .e("vifeco", map()
                    .e("view", "org.laeq.VifecoView")
                )
                .e("menu", map()
                    .e("model", "org.laeq.MenuModel")
                    .e("view", "org.laeq.MenuView")
                    .e("controller", "org.laeq.MenuController")
                )
                .e("middle", map()
                        .e("model", "org.laeq.template.MiddlePaneModel")
                        .e("view", "org.laeq.template.MiddlePaneView")
                        .e("controller", "org.laeq.template.MiddlePaneController")
                )
                .e("bottom", map()
                        .e("model", "org.laeq.BottomModel")
                        .e("view", "org.laeq.BottomView")
                        .e("controller", "org.laeq.BottomController")
                )
                .e("user_container", map()
                        .e("model", "org.laeq.user.ContainerModel")
                        .e("view", "org.laeq.user.ContainerView")
                        .e("controller", "org.laeq.user.ContainerController")
                )
                .e("category_container", map()
                        .e("model", "org.laeq.category.ContainerModel")
                        .e("view", "org.laeq.category.ContainerView")
                        .e("controller", "org.laeq.category.ContainerController")
                )
                .e("collection_container", map()
                        .e("model", "org.laeq.collection.ContainerModel")
                        .e("view", "org.laeq.collection.ContainerView")
                        .e("controller", "org.laeq.collection.ContainerController")
                )
                .e("video_list", map()
                        .e("model", "org.laeq.video.VideoListModel")
                        .e("view", "org.laeq.video.VideoListView")
                        .e("controller", "org.laeq.video.VideoListController")
                )
                .e("video_player", map()
                        .e("model", "org.laeq.video.PlayerModel")
                        .e("view", "org.laeq.video.PlayerView")
                        .e("controller", "org.laeq.video.PlayerController")
                )
                .e("controls", map()
                        .e("model", "org.laeq.video.ControlsModel")
                        .e("view", "org.laeq.video.ControlsView")
                        .e("controller", "org.laeq.video.ControlsController")
                )
                .e("category", map()
                        .e("model", "org.laeq.video.CategoryModel")
                        .e("view", "org.laeq.video.category.CategoryView")
                        .e("controller", "org.laeq.video.CategoryController")
                )
                .e("database", map()
                        .e("controller", "org.laeq.db.DatabaseController")
                )
                .e("category_create", map()
                        .e("model", "org.laeq.category.CategoryModel")
                        .e("view", "org.laeq.category.CategoryView")
                        .e("controller", "org.laeq.category.CategoryController")
                )
                .e("category_list", map()
                        .e("model", "org.laeq.category.CategoryListModel")
                        .e("view", "org.laeq.category.CategoryListView")
                        .e("controller", "org.laeq.category.CategoryListController")
                )
                .e("user_create", map()
                        .e("model", "org.laeq.user.UserModel")
                        .e("view", "org.laeq.user.UserView")
                        .e("controller", "org.laeq.user.UserController")
                )
                .e("user_list", map()
                        .e("model", "org.laeq.user.UserListModel")
                        .e("view", "org.laeq.user.UserListView")
                        .e("controller", "org.laeq.user.UserListController")
                )
                .e("category_collection_create", map()
                        .e("model", "org.laeq.category.CategoryCollectionModel")
                        .e("view", "org.laeq.category.CategoryCollectionView")
                        .e("controller", "org.laeq.category.CategoryCollectionController")
                )
            );
    }
}