name: Vifeco CI

on:
  push:
    branches:
      - actions

jobs:
  build:
    runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - name: Set up JDK 11
#         uses: actions/setup-java@v2
#         with:
#           distribution: 'zulu'
#           java-version: '11'
#           java-package: jdk+fx # optional (jdk, jre, jdk+fx or jre+fx) - defaults to jdk
#       - uses: eskatos/gradle-command-action@v1
#         with:
#           gradle-version: 6.3
#           wrapper-cache-enabled: true
#           dependencies-cache-enabled: true
#           configuration-cache-enabled: true
#           arguments: build
    steps:
      - name: Download JRE
      - run: wget https://download.bell-sw.com/java/11.0.15.1+2/bellsoft-jre11.0.15.1+2-linux-amd64-full.tar.gz

