name: Vifeco Debian Build

on:
  push:
    branches:
      - actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: 'liberica'
          java-version: '11'
          java-package: jdk+fx # optional (jdk, jre, jdk+fx or jre+fx) - defaults to jdk
      - name: Checkout
        uses: actions/checkout@v3
      - name: Gradle build
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 6.3
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: build

