name: Vifeco CI

on:
  push:
    branches:
      - actions

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Build package
        run: echo "This step will build the package"

